MODEL:
  META_ARCHITECTURE: "ClsResNet"
  BACKBONE:
    NAME: "build_rnet_backbone"
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ['res5']
    ENABLE: True
    NUM_CLASSES: 1000
    RES5_DILATION: 1
    STRIDE_IN_1X1: False
  CLSNET:
    INPUT_SIZE: 256
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  WEIGHTS: #'../../dump/fossil/imagenet/5mar-nor-stride/model_final.pth'
DATASETS:
  TRAIN: ("imagenet_train", )
  TEST: ("imagenet_val", )
DATALOADER:
  NUM_WORKERS: 3
  ASPECT_RATIO_GROUPING: False
SOLVER:
  IMS_PER_BATCH: 512
  BASE_LR: 0.1
  STEPS: (58500, 117000,)
  MAX_ITER: 234000
  WARMUP_FACTOR: .001
  WARMUP_ITERS: 1000
INPUT:
  CROP:
    ENABLED: True
    SIZE: [224, 224]
  FORMAT: "NOR"
TEST:
  AUG: 
    ENABLED: True
    MIN_SIZES: (224, 224, 224, 224, 224, 224, 224, 224, 224)
    MAX_SIZE: 256
    FLIP: True
  PRECISE_BN:
    ENABLED: False
OUTPUT_DIR : "../../dump/fossil/imagenet/18march-he/"
VERSION: 2